CREATE TABLE IF NOT EXISTS consignee (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS destination (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS bills (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bill_date TEXT NOT NULL,
  gst_percent REAL DEFAULT 0,
  gst_amount REAL DEFAULT 0,
  total REAL DEFAULT 0,
  grand_total REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS consignments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bill_id INTEGER NOT NULL,
  date TEXT NOT NULL,
  con_no TEXT NOT NULL,
  consignee TEXT NOT NULL,
  weight TEXT NOT NULL,
  destination TEXT NOT NULL,
  amount REAL DEFAULT 0,
  FOREIGN KEY (bill_id) REFERENCES bills(id) ON DELETE CASCADE
);
